project:
  type: website

website:
  title: "Silvia Canelón"
  site-url: https://silviacanelon.com
  description: "Researcher, educator, and journalist with data science expertise."
  favicon: assets/silvia/img/logo_rounded.svg
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@spcanelon"
    site: "@spcanelon"
    card-style: summary_large_image
  comments: 
    utterances: 
      repo: spcanelon/silvia 
      label: utterances
      theme: body-light
      issue-term: title

  navbar:
    logo: assets/silvia/img/logo_rounded.svg
    tools:
      - icon: github
        href: https://www.github.com/spcanelon/silvia
    right:
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Talks
        href: talk/index.qmd  
      - text: Publications
        href: publication/index.qmd
      - text: Projects
        href: project/index.qmd
  
  page-footer:  
    left: >-
      &#169; 2024 Silvia Canelón &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="/accessibility.html" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
      <a class="link-dark me-1" href="https://bsky.app/profile/silviacanelon.com" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/spcanelon" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/spcanelon" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0003-1709-1394" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=GAzkvpcAAAAJ&hl=en&oi=ao" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://buttondown.com/spcanelon" title="Newsletter" target="_blank" rel="noopener">{{< fa envelope >}}</a>
    right: 
      - text: "Accessibility"
        href: accessibility.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "License"
        href: license.qmd
      - icon: rss
        href: blog/index.xml

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/silvia-theme-light.scss
        # - assets/silvia/colors-light.scss
        # - assets/silvia/fonts.scss
      dark: 
        - cosmo
        - assets/silvia-theme-dark.scss
        # - assets/silvia/colors-dark.scss
    highlight-style:
      light: assets/silvia/a11y-light.theme
      dark: assets/silvia/a11y-dark.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute: 
  freeze: auto

# include-in-header: assets/silvia/umami.html
